# Site settings
title: UnJavaScripter's blog
email: ceo@vandelayindustries.com
description: > # this means to ignore newlines until "baseurl:"
  Diego Coy / UnJavaScripter's blog. JavaScript / AngularJS en español para noobs, porque todos lo fuimos en algún momento.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://unjavascripter.github.io/" # the base hostname & protocol for your site
twitter_username: unJavaScripter
github_username:  unJavaScripter
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown