# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: UnJavaScripter's blog
email: ceo@vandelayindustries.com
authorName: Diego Coy
description: > # this means to ignore newlines until "baseurl:"
  JavaScript, AngularJS y desarrollo web moderno en español. Diego Coy / UnJavaScripter
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://http://unjavascripter.github.io/" # the base hostname & protocol for your site
twitter_username: unJavaScripter
github_username:  unJavaScripter
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
