# Site settings
title: UnJavaScripter's blog
email: ceo@vandelayindustries.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://unjavascripter.github.io/" # the base hostname & protocol for your site
twitter_username: unJavaScripter
github_username:  unJavaScripter
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown